version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: prueba
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./app/
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://root:toor@db/prueba

  frontend:
    build: ./client/ 
    ports:
      - "5173:5173" 
    restart: always
    depends_on:
      - backend

volumes:
  pgdata:
